name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  create-release:
    runs-on: windows-latest
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}

    steps:
      - if: startsWith(github.ref, 'refs/tags/v')
        name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  rust:
    runs-on: ${{ matrix.os }}
    needs: create-release

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            library-file: libximu3.a
            target: i686-unknown-linux-gnu
          - os: ubuntu-latest
            library-file: libximu3.a
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            library-file: libximu3.a
            target: x86_64-unknown-linux-gnu

#          - os: macos-latest
#            library-file: libximu3.a
#          - os: windows-latest
#            library-file: ximu3.lib

    steps:
      - uses: actions/checkout@v2

      - name: Setup Linux
        run: sudo apt-get install libudev-dev

      - name: Build
        env:
          PKG_CONFIG_SYSROOT_DIR: /
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --manifest-path=x-IMU3-API/Rust/Cargo.toml --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        with:
          name: rust-${{ matrix.target }}
          path: x-IMU3-API/Rust/target/${{ matrix.target }}/release/libximu3.a

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Zip library
        run: |
          cd x-IMU3-API/Rust/target/${{ matrix.target }}/release/
          zip -r libximu3-${{ matrix.target }}.zip libximu3.a

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: x-IMU3-API/Rust/target/release/${{ matrix.library-file }}
          asset_name: ${{ matrix.library-file }}
          asset_content_type: application/octet-stream

  python:
    runs-on: ${{ matrix.os }}
    needs: rust

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            library-file: libximu3.a
            target: i686-unknown-linux-gnu
          - os: ubuntu-latest
            library-file: libximu3.a
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            library-file: libximu3.a
            target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: rust-${{ matrix.target }}
          path: x-IMU3-API/Rust/target/release

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine
          python -m pip install wheel

      - name: Build and install Python package
        run: |
          cd x-IMU3-API/Python
          python setup.py install --user
#
#  cmake:
#    runs-on: ${{ matrix.os }}
#    needs: [create-release, rust]
#
#    strategy:
#      fail-fast: false
#      matrix:
#        include:
#          - os: macos-latest
#            gui-file: x-IMU3 GUI.zip
#          - os: windows-latest
#            gui-file: x-IMU3 GUI.exe
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/download-artifact@v3
#        with:
#          name: rust-${{ matrix.os }}
#          path: x-IMU3-API/Rust/target/release
#
#      - name: Build targets
#        run: |
#          mkdir cmake-build-release
#          cd cmake-build-release
#          cmake .. -DCMAKE_BUILD_TYPE=Release
#          cmake --build . --target C-Examples Cpp-Examples x-IMU3-GUI --config Release
#
#      - if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'macos-latest'
#        name: Zip GUI (macOS)
#        run: |
#          cd cmake-build-release/x-IMU3-GUI/x-IMU3-GUI_artefacts/Release/
#          zip -r "x-IMU3 GUI.zip" "x-IMU3 GUI.app"
#
#      - if: startsWith(github.ref, 'refs/tags/v')
#        name: Upload GUI
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ needs.create-release.outputs.upload_url }}
#          asset_path: cmake-build-release/x-IMU3-GUI/x-IMU3-GUI_artefacts/Release/${{ matrix.gui-file }}
#          asset_name: ${{ matrix.gui-file }}
#          asset_content_type: application/octet-stream
